/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Departments: () => import('#controllers/departmen_controller'),
  Employees: () => import('#controllers/employees_controller'),
  Positions: () => import('#controllers/positions_controller')
}
